{{- if .Values.gateway.enabled -}}
{{- $gatewayName := default (include "namemaster.fullname" .) .Values.gateway.name -}}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ $gatewayName }}
  labels:
    {{- include "namemaster.labels" . | nindent 4 }}
  {{- with .Values.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  gatewayClassName: {{ .Values.gateway.className | quote }}
  {{- if or .Values.gateway.infrastructure.annotations .Values.gateway.infrastructure.labels }}
  infrastructure:
    {{- with .Values.gateway.infrastructure.annotations }}
    annotations:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.gateway.infrastructure.labels }}
    labels:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      {{- with .Values.gateway.hostname }}
      hostname: {{ . | quote }}
      {{- end }}
      allowedRoutes:
        namespaces:
          from: Same
    {{- if .Values.gateway.tls.enabled }}
    - name: https
      port: 443
      protocol: HTTPS
      {{- with .Values.gateway.hostname }}
      hostname: {{ . | quote }}
      {{- end }}
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: {{ .Values.gateway.tls.secretName | quote }}
      allowedRoutes:
        namespaces:
          from: Same
    {{- end }}
{{- end }}
