{{- if .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "namemaster.fullname" . }}-privileged
rules:
- apiGroups: ["", "extensions", "autoscaling", "apps", "batch", "events", "networking.k8s.io", "certmanager.k8s.io", "cert-manager.io", "monitoring.coreos.com", "rbac.authorization.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "namemaster.fullname" . }}-privileged
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "namemaster.fullname" . }}-privileged
subjects:
  - kind: ServiceAccount
    name: {{ .Values.rbac.serviceaccount.name }}
{{- end }}