apiVersion: v1
kind: Secret
metadata:
  name: {{ template "namemaster.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "namemaster.name" . }}
    helm.sh/chart: {{ include "namemaster.chart" . }}
type: Opaque
data:
  postgresql-username: {{ .Values.postgresql.username | b64enc | quote }}
  postgresql-password: {{ .Values.postgresql.password | b64enc | quote }}
  postgresql-host: {{ .Values.postgresql.host | b64enc | quote }}
  postgresql-port: {{ .Values.postgresql.port | b64enc | quote }}
  postgresql-database: {{ .Values.postgresql.database | b64enc | quote }}
  namemaster-secretkey: {{ .Values.namemaster.secretkey | b64enc | quote }}