apiVersion: v1
kind: Service
metadata:
  name: {{ include "namemaster.fullname" . }}
  labels:
    {{- include "namemaster.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP
      name: namemaster
  selector:
    {{- include "namemaster.selectorLabels" . | nindent 4 }}
