{{- if .Values.rbac.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rbac.serviceaccount.namesecret }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.rbac.serviceaccount.name }}
type: kubernetes.io/service-account-token
{{- end }}