apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubernetes-monitor
  namespace: monitoring
  labels:
    app.kubernetes.io/name: kubernetes-monitor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kubernetes-monitor
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
