variables:
  IMAGE_NAME: daniil3680/namemaster
  IMAGE_TAG: 0.0.2-R1

stages:
  - test
  - docker_deploy
test:
  image:
    name: docker/compose:latest
  services:
    - docker:dind
  stage: test
  tags:
    - kuber_gitlab-runner
  before_script:
      - docker version
      - docker-compose version
  script:
    - docker-compose build
    - docker-compose -f docker-compose.test.yaml up --exit-code-from web
docker_deploy: 
  image: docker:20.10.16
  stage: docker_deploy
  tags:
    - kuber_gitlab-runner
  # variables:
  #   DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG 



