image: rbekker87/build-tools:latest

stages:
  - ver
  - init
  - tests

ver:
  stage: ver
  script:
    - python --version
    - whoami

init:
  stage: init
  script:
    - apk add postgresql-dev --no-cache
    - pip install psycopg2-binary
    - pip install -r requirements.txt

run_tests:
  stage: tests
  script:
    - apk add postgresql-dev --no-cache
    - pip install psycopg2-binary
    - ls
    - pip install -r app/requirements.txt
    - python app/tests/unittest.py
