image: creatiwww/docker-compose:latest
stages:
  - test

services:
  - docker:dind

before_script:
  - apt-get update -qy
  - apt-get install -y docker-compose
test:
  stage: test
  script:
    - docker-compose build
    - docker-compose -f docker-compose.test.yaml up
   

# after_script:
#   - docker-compose down


