image: creatiwww/docker-compose:latest
stages:
  - test

services:
  - docker:dind

before_script:
  - apk add --no-cache docker-compose
test:
  stage: test
  script:
    - docker-compose build
    - docker-compose -f docker-compose.test.yaml up --exit-code-from web
   



