stages:
  - test

variables:
  FLASK_ENV: "testing"
  FLASK_APP: "your_app:create_app"
  DOCKER_IMAGE_NAME: "your-dockerhub-username/your-docker-image"
  DOCKER_IMAGE_TAG: "latest"
  KUBE_NAMESPACE: "your-kube-namespace"
  KUBE_CONFIG: "your-kube-config" # Содержимое файла kubeconfig, base64 закодированное
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "password"
  POSTGRES_HOST: "db"
  POSTGRES_PORT: "5432"
  username: postgres
  password: password
  host: db
  port: 5432
  database: mydatabase

before_script:
  - ls
  - apt-get update -qy
  - apt-get install -y python3-pip python3-dev
  - apt install python3-venv
  - python3 -m venv env

test:
  stage: test
  script:
    - ls
    - source venv/bin/activate
    - pip install -r requirements.txt
    - flask db upgrade
    - pytest
