stages:
  - test
  - docker_deploy
variables:
  IMAGE_NAME: daniil3680/namemaster
  IMAGE_TAG: 0.0.2-R1
services:
  - docker:25.0.1-dind

test:
  image: creatiwww/docker-compose:latest
  stage: test
  before_script:
    - apk add --no-cache docker-compose
  script:
    - docker-compose build
    - docker-compose -f docker-compose.test.yaml up --exit-code-from web
docker_deploy: 
  image: docker:25.0.1
  stage: docker_deploy
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG 



