image: python:3.8
stages:
  - test

variables:
  POSTGRES_DB: "your_db_name"
  POSTGRES_USER: "your_db_user"
  POSTGRES_PASSWORD: "your_db_password"
  FLASK_ENV: "testing"
  FLASK_APP: "your_app:create_app"

services:
  - docker:19.03.13-dind

before_script:
  - apk add --no-cache docker-compose
  - docker-compose -f docker-compose.test.yaml up 
test:
  stage: test
  script:
    - cd app/tests
    - docker ps
   

# after_script:
#   - docker-compose down


