stages:
  - test
  - docker_deploy
variables:
  IMAGE_NAME: daniil3680/namemaster
  IMAGE_TAG: 0.0.2-R1


test:
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  stage: test
  tags:
    - kuber_gitlab-runner
  script:
    - echo "{\"auths\":{\"$IMAGE_NAME\":{\"username\":\"$REGISTRY_USER\",\"password\":\"$REGISTRY_PASS\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
docker_deploy: 
  image: docker:25.0.1
  stage: docker_deploy
  tags:
    - kuber_gitlab-runner
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG 



