stages:
  - test

services:
  - docker:dind

before_script:
  - apk add --no-cache docker-compose 
test:
  stage: test
  script:
    - docker-compose -f docker-compose.test.yaml up
   

# after_script:
#   - docker-compose down


