version: '3'

services:
  web:
    image: python:3.10.12-slim
    command: bash -c "pip install --upgrade pip && pip install --no-cache-dir -r app/requirements.txt && pytest app/tests/unittest.py"
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
        postgresql-username: postgres
        postgresql-password: password
        postgresql-host: db
        postgresql-port: 5432
        postgresql-database: mydatabase

  db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: