{{- if and .Values.loadTest.token (not .Values.loadTest.existingSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "namemaster-locust.fullname" . }}
  labels:
    {{- include "namemaster-locust.labels" . | nindent 4 }}
type: Opaque
data:
  load-test-token: {{ .Values.loadTest.token | b64enc | quote }}
{{- end }}
