{{- if .Values.certificate.enabled }}
{{- $dnsNames := .Values.certificate.dnsNames }}
{{- if not $dnsNames }}
{{- $dnsNames = .Values.gateway.httpRoute.hostnames }}
{{- end }}
{{- if not $dnsNames }}
{{- $dnsNames = list (include "kubernetes-monitor.hostname" .) }}
{{- end }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.name }}
  namespace: {{ .Values.certificate.namespace }}
  labels:
    {{- include "kubernetes-monitor.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.certificate.secretName }}
  dnsNames:
    {{- toYaml $dnsNames | nindent 4 }}
  issuerRef:
    kind: {{ .Values.certificate.issuerRef.kind }}
    name: {{ .Values.certificate.issuerRef.name }}
{{- end }}
