global:
  domain: opsbox.org

gateway:
  enabled: true
  name: public
  namespace: nginx-gateway
  gatewayClassName: nginx
  annotations: {}
  labels: {}
  infrastructure:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
      service.beta.kubernetes.io/aws-load-balancer-attributes: load_balancing.cross_zone.enabled=true
    labels: {}
  listeners:
    - name: namemaster-http
      hostnameKey: namemaster
      hostname: ""
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - name: namemaster-https
      hostnameKey: namemaster
      hostname: ""
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: namemaster-tls
      allowedRoutes:
        namespaces:
          from: All
    - name: monitoring-http
      hostnameKey: monitoring
      hostname: ""
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - name: monitoring-https
      hostnameKey: monitoring
      hostname: ""
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: monitoring-tls
      allowedRoutes:
        namespaces:
          from: All

certificates:
  - enabled: true
    name: namemaster
    namespace: nginx-gateway
    secretName: namemaster-tls
    hostnameKey: namemaster
    dnsNames: []
    issuerRef:
      kind: ClusterIssuer
      name: letsencrypt-prod
  - enabled: true
    name: monitoring
    namespace: nginx-gateway
    secretName: monitoring-tls
    hostnameKey: monitoring
    dnsNames: []
    issuerRef:
      kind: ClusterIssuer
      name: letsencrypt-prod
