# Default values for namemaster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: daniil3680/namemaster
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest


# Creates a ServiceAccount for the ability to install and modify resources in namespace: namemaster using gitlab runner.
# The token is written to the secret "namemaster-serviceaccount-secret".

rbac:
  create: false
  serviceaccount:
    name: namemaster-serviceaccount
    annotations: {}
    namesecret: namemaster-serviceaccount-secret

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: 
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts: {}
    # - host: example.online
    #   paths:
    #     - path: /
    #       pathType: Prefix
  tls: []
  #  - secretName: namemaster-tls
  #    hosts:
  #      - example.online

# You need to enter data from your postgresql
# This data will be entered into the secret for working with the namemaster database

postgresql:
  username: postgres
  password: db_password
  host: postgresql
  port: '5432'
  database: postgres

# secret key for namemaster operation
namemaster:
  secretkey: 9b908738adb74b789012511dce6e0bfe # example

# Pod limits
resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Enable pod autoscaling using HorizontalPodAutoscaler
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
