{{- range .Values.certificates }}
{{- if .enabled }}
{{- $dnsNames := .dnsNames }}
{{- if not $dnsNames }}
{{- $dnsNames = list (include "shared-gateway.hostname" (dict "root" $ "key" .hostnameKey "value" .hostname)) }}
{{- end }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  labels:
    app.kubernetes.io/name: {{ $.Chart.Name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
spec:
  secretName: {{ .secretName }}
  dnsNames:
    {{- toYaml $dnsNames | nindent 4 }}
  issuerRef:
    kind: {{ .issuerRef.kind }}
    name: {{ .issuerRef.name }}
{{- end }}
{{- end }}
